if(NOT CMAKE_SYSTEM_NAME STREQUAL "iOS")
    message(FATAL_ERROR "SENTRY_QML_SDK=ios is only supported when building for iOS.")
endif()

set(SENTRY_IOS_MINIMUM_DEPLOYMENT_TARGET "15.0" CACHE STRING
    "Minimum iOS deployment target supported by Sentry Cocoa"
)

if(CMAKE_OSX_DEPLOYMENT_TARGET
        AND CMAKE_OSX_DEPLOYMENT_TARGET VERSION_LESS SENTRY_IOS_MINIMUM_DEPLOYMENT_TARGET)
    message(FATAL_ERROR
        "SENTRY_QML_SDK=ios requires CMAKE_OSX_DEPLOYMENT_TARGET "
        "${SENTRY_IOS_MINIMUM_DEPLOYMENT_TARGET} or higher."
    )
endif()

if(NOT CMAKE_XCODE_ATTRIBUTE_IPHONEOS_DEPLOYMENT_TARGET)
    set(CMAKE_XCODE_ATTRIBUTE_IPHONEOS_DEPLOYMENT_TARGET "${SENTRY_IOS_MINIMUM_DEPLOYMENT_TARGET}")
endif()

include("${PROJECT_SOURCE_DIR}/cmake/cocoa.cmake")
