name: Update Dependencies

on:
  schedule:
    - cron: '30 3 * * 1'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  actions: write

jobs:
  sentry-sdks:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Sentry Native SDK
            path: modules/sentry-native
            pattern: '^v?[0-9]+\.[0-9]+\.[0-9]+$'
          - name: Sentry Cocoa SDK
            path: modules/sentry-cocoa
            pattern: '^v?[0-9]+\.[0-9]+\.[0-9]+$'
    steps:
      - uses: getsentry/github-workflows/updater@26f565c05d0dd49f703d238706b775883037d76b # v3
        with:
          name: ${{ matrix.name }}
          path: ${{ matrix.path }}
          pattern: ${{ matrix.pattern }}
          changelog-entry: false
          api-token: ${{ secrets.CI_GITHUB_TOKEN }}
          ssh-key: ${{ secrets.CI_DEPLOY_KEY }}

  self-hosted:
    name: Sentry self-hosted
    runs-on: ubuntu-latest
    steps:
      - uses: getsentry/github-workflows/updater@26f565c05d0dd49f703d238706b775883037d76b # v3
        with:
          name: Sentry self-hosted
          path: modules/self-hosted.properties
          pattern: '^v?[0-9]+\.[0-9]+\.[0-9]+$'
          post-update-script: scripts/update-self-hosted.sh
          changelog-entry: false
          api-token: ${{ secrets.CI_GITHUB_TOKEN }}
          ssh-key: ${{ secrets.CI_DEPLOY_KEY }}

  qt:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Qt LTS
            path: modules/qt-lts.properties
            pattern: '^v?6\.8\.\d+$'
          - name: Qt stable
            path: modules/qt-stable.properties
            pattern: '^v?6\.\d+\.\d+$'
    steps:
      - uses: getsentry/github-workflows/updater@26f565c05d0dd49f703d238706b775883037d76b # v3
        with:
          name: ${{ matrix.name }}
          path: ${{ matrix.path }}
          pattern: ${{ matrix.pattern }}
          post-update-script: scripts/update-qt.sh
          changelog-entry: false
          api-token: ${{ secrets.CI_GITHUB_TOKEN }}
          ssh-key: ${{ secrets.CI_DEPLOY_KEY }}
